deploymentversion/deployable/api/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from django.contrib import admin
from . import views

urlpatterns = [
 	url(r'^v1$',         views.api,      	 name='api'),
    url(r'^v1/games$',     views.games,      name='allgames'),
    url(r'^v1/stats$',     views.stats,      name='stats'),
    url(r'^v1/highscores$',views.highscores, name='highscores'),
]
#Names need clearn up, just for consistence view

deploymentversion/deployable/deployable/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^members/'   , include('members.urls')),
        url(r'^gamesite/'  , include('gamesite.urls')),
        url(r'^gamecenter/', include('gamecenter.urls')),
        url(r'^messaging/' , include('messaging.urls')),
        url(r'^utilities/' , include('utilities.urls')),
		url(r'^api/' , include('api.urls')),
        url(r'^$^', RedirectView.as_view(url='/gamesite/', permanent=True)),
        url('^accounts/', include('django.contrib.auth.urls')),
        url('', include('social_django.urls', namespace='social'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

deploymentversion/deployable/gamecenter/urls.py
from django.conf.urls import url
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib import admin
from . import views
from .views import register, logging_in,logging_out,activation,developer_games,player_games
from .views import addgame, updategame, GameListView, GameDetailView, deletegame, play_game_view,purchase_game, \
payment_success,payment_error,payment_cancel
urlpatterns = [
    url(r'^addgame/$',addgame,name='addgame'),
    url(r'^games/$', views.GameListView.as_view(),name='games'),
    #url(r'^search/(?P<game_name>[\w\-]+)/$', views.GameSearchView.as_view(),name='search'),

    url(r'^updategame/(?P<game_name>[\w\-]+)/$',updategame,name="updategame"),
    url(r'^deletegame/(?P<game_name>[\w\-]+)/$',deletegame,name="deletegame"),

    url(r'^developergames',    developer_games,   name='developergames'),
    url(r'^playergames',       player_games,      name='playergames'),

    #url(r'^playgame/([0-9]+)/$',play_game_view, name='playgame'),
    url(r'^game/(?P<pk>\d+)$',views.GameDetailView.as_view(),name='game-detail'),
    url(r'^playgame/(?P<game_name>[\w\-]+)/$',    play_game_view,name="playgame"   ),



    url(r'^purchase/(?P<game_name>[\w\-]+)/$', purchase_game,name="purchase"),
    url(r'^testgame/', TemplateView.as_view(template_name="gamecenter/teachers_example_game.html"),name='testgame'),
    url(r'^testgame/', TemplateView.as_view(template_name="gamesite/sampleGame.html"),name='testgame'),

    url(r'^paysuccess',  payment_success, name='paysuccess'),
    url(r'^payerror/$'  ,payment_error,   name='payerror'),
    url(r'^paycancel/$', payment_cancel,  name='paycancel'),
]
#Names need clearn up, just for consistence view

deploymentversion/deployable/gamecenter/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from members.models import Member
# A game knows its developer [a single developer]
# Games are stored elsewhere, indicated by game_url. 
# The default game is the one given by course staff. 
# The game is shown in an iframe in the play page. 
import logging
logger = logging.getLogger(__name__)

class Game(models.Model):
    game_name        = models.CharField(max_length=25, blank=False, unique=True, verbose_name="Name")
    max_score        = models.FloatField(verbose_name="Maximum score", default=0.0)  
    sales_counter    = models.PositiveIntegerField(verbose_name="purchase count", default=0)   
    price            = models.FloatField(verbose_name="Price")   
    upload_date      = models.DateField(auto_now=False, auto_now_add=False,verbose_name="Upload date", default=timezone.now)   
    game_description = models.CharField(max_length=25, verbose_name="Game description")
    game_url         = models.URLField(max_length=255, verbose_name="Game url", default="https://git.niksula.hut.fi/oseppala/wsd2016/blob/master/examples/example_game.html")
    developer        = models.ForeignKey(Member, related_name="game_reverse_lookup", on_delete=models.CASCADE, verbose_name="Developer")

    class Meta:
        verbose_name        = 'Game'
        verbose_name_plural = 'Games'

    def __str__(self):
        return self.game_name

    def getMaxScore(self):
        return  self.max_score

    def getSales(self):
        return  self.sales_counter * self.price

    def setMaxScore(self,score):#comes from the state
        logger.debug("Inside setter of game")
        self.max_score = score
        self.save()

    def get_absolute_url(self):
        return reverse('game-detail', args=[str(self.id)])

    def high_scores(self):
        highscores = {}
        highscore  = {}
        game_list = []
        if  State.objects.filter(game=self).first() is not None:#this game is purchased at least once. 
            all_states = State.objects.filter(game=self).order_by('-score')[:10] #get it out
            for state in all_states:
                highscore["name"]   = state.player.first_name
                highscore["score"]  = state.score
                game_list.append(highscore)
                highscore = {}
            highscores["allscores"] = game_list
            return highscores
        return None
#   The state of a gave with respect to a given player is shown below. 
#   (plaer, game) is unique and serves as a key.
#   Entry is created once for player's who purchsed the game.
#   Access control is not done here.
class State(models.Model):
    player    = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name="Player",related_name="state_reverse_lookup")
    game      = models.ForeignKey(Game,on_delete=models.CASCADE, verbose_name="Game")
    score     = models.FloatField(verbose_name="score")   #different from the maximum score which is one per game
    items     = models.TextField(blank=True)          #itesm separated by @ symbol
    purchase_date      = models.DateField(auto_now=False, auto_now_add=False,verbose_name="purchase date", default=timezone.now)   

    class Meta:
        verbose_name        = 'State'
        verbose_name_plural = 'States'
        unique_together     = ("player", "game")

    def __str__(self):
        return self.player.email + ' ,' + self.game.game_name # used for comparison')''
    #Getter and setter for items of a player's game
    def setItems(self, items):
        self.items = items

    def getItems(self):
        return self.items
    #Getter and setter for score of a player's game
    def setScore(self,score):
        self.score = score
        #make sure it set, then compare with 'global' score, update if needed.
        game = self.game#Game.objects.get(gname=self.game_name)    #get an actual game object and update it.
        if float(self.score) > float(game.getMaxScore()):
            game.setMaxScore(self.score)    #for consistency

        #logger.debug("======================", game.getMaxScore())
        #logger.debug("======================", self.score)

    def getScore(self):
            return  self.score

    def get_absolute_url(self): # a player is not a member here.
        return reverse('state-detail', args=[str(self.pk)])

    def get_game_state(self):    #a game should know its state with respect to a given player.
        try:
            oneString   = self.getItems()
            playerItems = oneString.split("@") #Save as a single string separated by @
            score       = self.getScore()
            currentSate = {}
            gameState   = {}
            logger.debug("processing collected items for: ",self.game)
            gameState['playerItems'] = playerItems
            gameState['score']       = score
            #raise ValueError('k') Testing error message
            currentSate['messageType']  = "LOAD"
            currentSate['gameState']    = gameState
        except: #whatever the reason.BUT, game is found, only loading sate has failed.
            currentSate =  {
                "messageType": "ERROR",
                "info": "Gamestate could not be loaded"
            };
        return currentSate


# Track confirmed payments. Half processed payments are ignored.     
#A player shall not buy the same game twice, protected by the 'unique_together'
#pid may result in many half prococessed transactions, could be analyzed to see how many has failed 
class Transaction(models.Model):
    player        = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name="player")
    game          = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name="game")
    pid           = models.CharField(max_length=25, blank=True, unique=False, verbose_name="pid")
    is_success    = models.BooleanField(default=False, verbose_name="Transaction complete",blank=True)

    class Meta:
        verbose_name        = 'Transaction'
        verbose_name_plural = 'Transactions'
        unique_together = ('player', 'game',)#For preventing re-purchasing the same game.

    def __str__(self):
        return '( '+self.player.email + ' , ' + self.game.game_name +')'

deploymentversion/deployable/gamecenter/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import authenticate
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core import mail
import uuid
from django.db import models
from django.contrib.auth.models import User
from members.models import Member
from gamecenter.models import Game
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
import logging
logger = logging.getLogger(__name__)
class GameAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GameAddForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })
    class Meta:
        model = Game
        fields = ['game_name','price','game_description','game_url','developer']

class GameUpdateForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = ['game_name','price','game_description']

class GameDeleteForm(forms.ModelForm):

    actions = (
        ('delete', 'delete'), #how about adding modify action or new actions
    )
    choice = forms.MultipleChoiceField(required=False,
                                       widget=forms.CheckboxSelectMultiple,
                                       choices=actions,
                                       )
    class Meta:
        model = Game
        fields = ['game_name','price','game_description']

class member_register(UserCreationForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    user_type = (
        ('players', 'player'),
        ('developers', 'developer'),
    )
    group =  forms.ChoiceField(label='Account type',choices=user_type, required=True)
    class Meta:
        model = Member
        fields = ('email', 'username','first_name','last_name',) #what else ? Street address.....
    #requires validation
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        #check if user exists. 
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(member_register, self).save(commit=False)
        user.email  = self.cleaned_data.get("email")
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_active = False
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
            chosen = self.cleaned_data.get("group")
            #group = Group.objects.get_or_create(name=chosen)
            group = Group.objects.get(name=chosen)
            user.groups.add(group)

            eemail  = self.cleaned_data.get("email")
            code =str(uuid.uuid4())[0:24]
            mailer(self,code,eemail)
            #activation code is saved for future reference
            active = ActivationData.objects.filter(email=eemail)
            if not active:
                ActivationData.objects.create(email=eemail, activation_code=code).save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Member
        fields = ('email', 'password','first_name','last_name', 'is_active')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class loginForm(forms.Form):
    email       = forms.CharField(label='email')
    password    = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self,*args,**kwargs):
        #get values from the form
        username        = self.cleaned_data.get("email") #username is an email
        password        = self.cleaned_data.get("password")
        #retrieve user from db.
        user = Member.objects.filter(email=username)
        if not user:
            raise forms.ValidationError("In valid username or password") #do not get specific
        else:
            user = Member.objects.filter(email=username).first()#get it out
            if user.check_password(password):
                #match found
                #check if account is activated.
                if not user.is_active:
                    raise forms.ValidationError("In active account, please check your email for the activation code")
                #an active account
                return super(loginForm, self).clean(*args, **kwargs)
            else:
                raise forms.ValidationError("In valid username or password") #do not get specific

class ActivationForm(forms.Form):
    email   = forms.CharField(label='email')
    code    = forms.CharField(label='Activation code') #code

    def clean(self,*args,**kwargs):
        #get values from the form
        email        = self.cleaned_data.get("email") #username is an email
        code         = self.cleaned_data.get("code")
        #retrieve user from db.
        user = ActivationData.objects.filter(email__iexact=email)
        if not user:
            raise forms.ValidationError("unknown email, please make a registration.") #do not get specific
        else:
            user = ActivationData.objects.filter(email=email).first()#get it out
            logger.debug(user.activation_code)
            logger.debug(code)
            if not user.activation_code == code:
                raise forms.ValidationError("Incorrect activation key.")

            else: #activate the account
                    #no need to check again, if active, would not hurt to activate it again.
                    logger.debug("We are activating your account. ....")
                    account = Member.objects.filter(email=email).first()#get it out
                    account.is_active = True
                    account.save()
                    #an active account
        return super(ActivationForm, self).clean(*args, **kwargs)

def mailer(self,code,email):
    connection = mail.get_connection()
    # Manually open the connection
    connection.open()
    # Construct an email message that uses the connection
    email1 = mail.EmailMessage(
        'Activation code for '+email,
        'Please use this code to activate your account: ' + code,
        'admin@gamestore.com',
        [email],
        connection=connection,
        )
    email1.send()  # Send the email

deploymentversion/deployable/gamecenter/templates/gamecenter/deletegame.html
{% extends "base.html" %}
{% block content %}
<h1>Remove game from the Game store.</h1>
	<div class="row">
		<div class="col-xs-8">
			<form action="." method="post">{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<span class="label label-primary">{{ field.label }}</span>{{ field }}
					</div>
				{% endfor %}
				 <input type="submit" class="btn btn-danger" value="Delete Game">

			</form>
		</div>
	</div>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/error.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
<ul class="alert alert-danger">
    {% for message in messages %}
    <br>{{ message }}
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/game_detail.html
{% extends "base.html" %}
{% block content %}
  <p><strong>Name:</strong> {{ game.game_name }}</p>
  <p><strong>Description:</strong> {{ game.game_description }}</p>
  <p><strong>Developer:</strong> {{ game.developer }}</p>
  <p><strong>Highest score:</strong> {{ game.max_score }}</p>
  <p><strong>Sales count:</strong> {{ game.sales_counter }}</p>
  <p><strong>Price:</strong> {{ game.price }}</p>
  <div class="btn-group btn-group-justified">
    <a href="{% url 'purchase'    game.game_name %}" class="btn btn-primary">Buy  Game</a>
    <a href="{% url 'playgame'    game.game_name %}" class="btn btn-primary">Play  Game</a>
    <a href="{% url 'addgame' %}" class="btn btn-primary">Add  Game</a>
    <a href="{% url 'updategame'  game.game_name %}" class="btn btn-primary">Edit Game</a>
    <a href="{% url 'deletegame'  game.game_name %}" class="btn btn-primary btn btn-danger">Delete Game</a>
</div>
{% endblock %}

{% block side-up %}
<h3>High scores</h3>
{% for onescore in game.high_scores.allscores %}
{{onescore.name}}  {{onescore.score}}<br>
{%endfor%}
{% endblock %}

{% block side-down %}
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/game_list.html
{% extends "base.html" %}
{% block content %}
<h1>Game List</h1>
    <form role="search" class="navbar-form navbar-center">
          <div class="form-group">
              <input type="text" placeholder="Search games" name="search" class="form-control">
          </div>
    </form>
    {% if game_list %}
    <table class="table table-striped">
        <thead>
        <tr>
        <th>Game</th>
        <th>Developer</th>
        <th>Description</th>
        <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for game in game_list %}
            <tr>
            <td><a href="{{ game.get_absolute_url }}">
            {{ game.game_name }}</a></td>
            <td>{{ game.developer.first_name }} {{ game.developer.last_name }}</td>
            <td>{{ game.game_description }}     </td>
            <td>{{ game.price }}     </td>
              <!--cllect developer's games-->
                {% for game in developer.game_reverse_lookup.all %}
                  <a href="{% url 'game-detail' game.pk %}">{{ game.game_name}}</a>

                  {% if not forloop.last %},

                  {% endif %}{% endfor %}
              <!--end of getting developer's games-->
            </tr>
        {% endfor %}
        </tbody>
        </table>
    {% else %}
         <p>There are no games in the system at the moment..</p>
    {% endif %}
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/gameadd.html
{% extends "base.html" %}
{% block content %}
	<h1>Add a new game to the Game store.</h1>
	<div class="row">
		<div class="col-xs-8">
			<form action="." method="post">{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<span class="label label-primary">{{ field.label }}</span>{{ field }}
					</div>
				{% endfor %}
				 <input type="submit" class="btn btn-primary" value="Add Game">
			</form>
		</div>
	</div>
{% endblock %}
{% comment "resources" %}
{{form.as_p}}
Modelform and bootstrap form
http://stackoverflow.com/questions/31627253/django-modelform-with-bootstrap

{% endcomment %}

deploymentversion/deployable/gamecenter/templates/gamecenter/gamemodify.html
{% extends "base.html" %}
{% block content %}
	<h1>update game information.</h1>
	<div class="row">
		<div class="col-xs-8">
			<form action="." method="post">{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
						<span class="label label-primary">{{ field.label }}</span>{{ field }}
					</div>
				{% endfor %}
				 <input type="submit" class="btn btn-primary" value="Update Game">

			</form>
		</div>
	</div>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/payment_cancel.html
{% extends "base.html" %}
{% block content %}
<h1>You transaction is cancelled...</h1>
<ul class="alert alert-warning">
<h1>Thank you for your purchase.....</h1>
pid:{{pid}}<br>
ref : {{ref}}<br>
result: {{result}}<br>
checksum: {{checksum}}<br>
</ul>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/payment_error.html
{% extends "base.html" %}
{% block content %}
<h1>You transaction has failed...</h1>
<ul class="alert alert-error">
<h1>Thank you for your purchase.....</h1>
pid:{{pid}}<br>
ref : {{ref}}<br>
result: {{result}}<br>
checksum: {{checksum}}<br>
</ul>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/payment_request.html
{% extends "base.html" %}
{% block content %}
<form action="http://payments.webcourse.niksula.hut.fi/pay/" method="post"> {% csrf_token %}
    <input type="hidden" name="pid" value={{pid}} />
    <input type="hidden" name="sid" value={{sid}} />
    <input type="hidden" name="success_url" value="https://hidden-bastion-98067.herokuapp.com/gamecenter/paysuccess/" />
    <input type="hidden" name="cancel_url"  value="https://hidden-bastion-98067.herokuapp.com/gamecenter/payerror/" />
    <input type="hidden" name="error_url"   value="https://hidden-bastion-98067.herokuapp.com/gamecenter/paycancel/" />
    <input type="hidden" name="checksum" value={{checksum}} />

    <label for="id_card">Credit card</label>
    <input type="text" id="id_card" name="card" value=""/>
    <br>

    <label for="id_game">Game</label>
    <input type="text" id="id_game" name="gamename" value={{game_name}} />
    <br>
    <label for="id_amount">Amount</label>
    <input type="text" id="id_amount" name="amount" value={{amount}} />
    <input type="submit" value="Accept Payment"/>
</form>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/payment_success.html
{% extends "base.html" %}
{% block content %}
<ul class="alert alert-success">
<h1>Thank you for your purchase.....</h1>
pid:{{pid}}<br>
ref : {{ref}}<br>
result: {{result}}<br>
checksum: {{checksum}}<br>
</ul>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/playgame.html
{% extends "base.html" %}
{% block content %}
<script type="text/javascript">
$(document).ready(function() {
    //How do we get player specific infor and game specific info
    var player_id = {{player_id}};
    var gamename  = "{{game_name}}";
    $( "#share" ).click(function() {
        window.open("https://www.facebook.com/dialog/feed?app_id=XXXXXXXXX&ref=site&display=page&name={{game_name}}&caption={{game_name}} is played by many&picture=https://i.stack.imgur.com/CLCRl.png&description=The best game ever&link=http://localhost/gamecenter/games/");
    });
    'use strict';
    $(window).on('message', function(evt) {
      var data = evt.originalEvent.data;
      //determine message type
      /*
          Get the score and save it,
          if value is bigger than current max for the game, then save it.
          if not save it for the palyer
      */
      if (data.messageType === "SCORE"){
          var newData = {}
          newData.messageType = data.messageType;
          newData.score       = data.score;
          newData.player_id   = player_id
          //only for debugging purpose.
          var score = data.score;
          //console.log("Sending new score to the platform, ", JSON.stringify(data));
          //
          console.log("request" + JSON.stringify(newData));
          $('#actions').append('\n\t<li>' + 'request: '+(JSON.stringify(newData) || '') + '</li>');
          //sending request to the server.
          //console.log(newData)
            $.ajax({
                "type": 'POST',
                //"contentType": 'application/json; charset=utf-8',
                "url": 'http://127.0.0.1:8000/messaging/savescore/' + gamename + '/',
                "data": newData,
                //crossDomain:true,
                success: function(result) {
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response: ' + JSON.stringify(result)+ '</li>');
                },error: function(result) {
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response :' + JSON.stringify(result)+ '</li>');
                }
          });//ending ajax
            //console.log(JSON.stringify(data)+'--------------------')
      }
      /*
          message contains items and score.
          send the message to the server,
          validatin also done on the server.
          validation on client not required, at least the input methods are save unless manipulated.
      */
      if (data.messageType === "SAVE"){
        //console.log("Sending new save request to the platform, ", JSON.stringify(data));
          //make a new data that is flattened.
          var newData = {}
          newData.messageType = data.messageType;
          newData.playerItems = data.gameState.playerItems.join('@');
          newData.score       = data.gameState.score;
          newData.player_id   = player_id

          console.log("request:" + JSON.stringify(newData));
          $('#actions').append('\n\t<li>' + 'request: '+(JSON.stringify(newData) || '') + '</li>');          $.ajax({
                "type": 'POST',
                //"contentType": 'application/json; charset=utf-8',
                "url": 'http://127.0.0.1:8000/messaging/savestate/' + gamename + '/',
                "data": newData,
                //crossDomain:true,
                success: function(result) {
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response: ' + JSON.stringify(result)+ '</li>');
                },error: function(result) {
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response :' + JSON.stringify(result)+ '</li>');
                }
          });//ending ajax
      }
      /*
        Retrieve everything the game has on the server.
        Then what ?
          How to give it back the state ?
          How to show game content for the player ?
      */
      if (data.messageType === "LOAD_REQUEST"){
          newData = {}
          newData.messageType = data.messageType;
          newData.player_id   = player_id
          console.log("request: " + JSON.stringify(newData));
          $('#actions').append('\n\t<li>' + 'request: '+(JSON.stringify(newData) || '') + '</li>');
            $.ajax({
                "type": 'POST',
                //"contentType": 'application/json; charset=utf-8',
                "url": 'http://127.0.0.1:8000/messaging/loadrequeset/' + gamename + '/',
                "data": newData,
                //crossDomain:true,
                success: function(result) {
                        //what to do with the result, not specified since we do not have
                        //control over the game
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response: ' + JSON.stringify(result)+ '</li>');
                },error: function(result) {
                        console.log('response' + JSON.stringify(result));
                        $('#actions').append('\n\t<li>' +'response :' + JSON.stringify(result)+ '</li>');
                }
          });//ending ajax
      }
      /*
          Handle resolution related request
          Either retrieve a game with the given resolution
          Or simulated by changing the iframe width and height.
          This seems to be the only one handled not on the server side.
      */
      if (data.messageType === "SETTING"){
          var newData = {}
          newData.player_id   = player_id

          newData.messageType = data.messageType;
          newData.width       = data.options.width
          newData.height      = data.options.height;
            //console.log("Sending SETTING request to the platform, ", JSON.stringify(data));
            var newItem = '\n\t<li>request: ' + (JSON.stringify(newData) || '') + '</li>';
            //$('#actions').prepend(newItem);

                $.ajax({
                    "type": 'POST',
                    //"contentType": 'application/json; charset=utf-8',
                    "url": 'http://127.0.0.1:8000/messaging/loadsetting/' +gamename +  '/',
                    "data": newData,
                    //crossDomain:true,
                    success: function(result) {
                            console.log('response' + JSON.stringify(result));
                            var width  = result.options.width
                            var height = result.options.height
                            //console.log(JSON.stringify(result));
                            $("#gameframe").width(width);
                            $("#gameframe").height(height);
                    },error: function(result) {
                            console.log('response' + JSON.stringify(result));
                    }
              });//ending ajax
      }
    });
  });
</script>
<h1>Play Game</h1>
  <iframe id="gameframe" src="{% url 'testgame' %}" width="600" height="300"></iframe>
  <ul id="actions">

  </ul>
  <input type="button" name="share" id="share" value="Share on facebook"/>
{% endblock %}

deploymentversion/deployable/gamecenter/templates/gamecenter/success.html
{% extends "base.html" %}
{% block content %}
{% if messages %}
<ul class="alert alert-success">
    {% for message in messages %}
    <br>{{ message }}
    {% endfor %}
</ul>
{% endif %}
{% endblock %}